export const adminPhoneNumber = ''
export const mobileAppPhoneNumber = ''
export const authPassword = ''
export const telegramBotApiToken = ''
export const telegramUpdateChannelChatId = ''
export const telegramInfoChannelChatId = ''
